volumes:
  db_data:

services:
  webontour:
    image: benjaminderprogrammierer/webontour:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webontour
    restart: unless-stopped
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      JWT_SECRET: ${JWT_SECRET}
      MASTER_SIGNUP_KEY: ${MASTER_SIGNUP_KEY}
      PORT: ${PORT:-3000}
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./server/attachments:/attachments
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 10s
      timeout: 10s
      retries: 5
  db:
    image: postgres:18-alpine
    container_name: webontour-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - db_data:/var/lib/postgresql/
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USER}"]
      interval: 10s
      timeout: 10s
      retries: 5
