services:
  updater:
    image: benjaminderprogrammierer/webontour-updater:latest
    container_name: webontour-updater
    restart: unless-stopped
    environment:
      - PORT=8080
      - WEBHOOK_SECRET=your_webhook_secret
    build:
      context: ./updater
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
