FROM node:lts-alpine

# Install cURL for health checks
RUN apk add --no-cache curl

# App data is later mounted to /app (node modules aren't though, install a fresh version of them.)

# Set working directory
WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

# Environment
ENV NODE_ENV=development
ENV PORT=3000
EXPOSE 3000

# Run the application
CMD ["npm", "run", "dev"]
